### ISSUE TITLE
Docker cannot read the "tokens.mem" file (English model)

### ISSUE THREAD

**Issue by ThisIsAlish** [dbpedia-spotlight/spotlight-docker#42]
After the model was downloaded and unzipped, I got this error in the container's logs:
<img width="1004" alt="Screen Shot 2022-06-16 at 11 42 08 am" src="https://user-images.githubusercontent.com/46294643/173976552-fa38b67a-90a9-4dd6-a7bb-2d35aff03c49.png">

Sorry I'm new to docker and don't know how to solve this problem.

**Comment by Julio-Noe** [comment]
Hi @irekahsila 

Usually, this error happens because of a download error. The download process is divided into two general steps:

1. Download the docker container
2. Download the corresponding language model

The error occurs in the second step. After downloading the docker container, it is executed the command to download the corresponding language model. If the download is interrupted, the process to start the services continues, and the DBpedia Spotlight tries to uncompress the model and read the files to start the service. As the model was not completely downloaded, then the files are not found by the DBpedia Spotlight service, and an error is thrown. 

Then, you need to delete the downloaded container and try the process again. I hope this information helps you.

**Comment by irekahsila** [comment]
Hi @Julio-Noe, 

Thank you very much for your fast reply and the clarification. 
I just deleted the container and did the process again. 

Cheers.

**Comment by irekahsila** [comment]
After deleting and creating another container, I still have the same problem.

<img width="1012" alt="Screen Shot 2022-06-16 at 1 52 48 pm" src="https://user-images.githubusercontent.com/46294643/173990875-43c526e8-cea0-4191-b28c-d93ced676e09.png">

@Julio-Noe, Do you have other suggestions about this issue?

**Comment by irekahsila** [comment]
I removed everything and did the process again for the third time and it worked finally. 
Thank you very much for your help @Julio-Noe 🙏🏻

**Comment by Julio-Noe** [comment]
Hi @irekahsila 

Great news! And thanks for the updates. About the last image, the message "`curl: (18) transfer closed with 125040681 bytes remaining to read`" indicates an error during the downloading process of the language model. We will work on that error to show an error message and stop the starting process of the DBpedia Spotlight service. Thanks again.

**Comment by junrui-z** [comment]
Hi @Julio-Noe I also have the same error, I tried multiple times to re-start the process after deleting everything but I think the container is still stopped when the model cannot be downloaded. I am not sure how to attach to the container if it's stopped right after the interruption of the model download, I was trying to manually copy paste the model files into the opt dir.
